import { SLOT_FALLBACK } from "./slots";
import type { Catalog, Partner, Product, SocialLink, Testimonial } from "./types";

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "dragon",
    name: "Dragon fruit",
    kind: "Fruit",
    season: "Peak Nov–Apr",
    note: "Organic pitaya from concrete pillars. A pillar can yield ~20 kg in season.",
    image: "/images/dragon.jpg",
    unit: "kg",
    priceMvr: 85,
    inStock: true,
    featured: true,
    sortOrder: 10,
    active: true,
  },
  {
    id: 2,
    slug: "cucumber",
    name: "Greenhouse cucumber",
    kind: "Greenhouse",
    season: "Year-round",
    note: "Long English cucumbers, harvested daily from hanging vines.",
    image: "/images/produce-cucumber.jpg",
    unit: "kg",
    priceMvr: 45,
    inStock: true,
    featured: true,
    sortOrder: 20,
    active: true,
  },
  {
    id: 3,
    slug: "tomato",
    name: "Vine tomato",
    kind: "Greenhouse",
    season: "Year-round",
    note: "Cluster tomatoes grown in autopot lines under island light.",
    image: "/images/produce-tomato.jpg",
    unit: "kg",
    priceMvr: 55,
    inStock: true,
    featured: true,
    sortOrder: 30,
    active: true,
  },
  {
    id: 4,
    slug: "greens",
    name: "Leaf & salad mix",
    kind: "Greenhouse",
    season: "Weekly",
    note: "Fast-turn greens for kitchens in Addu and Fuvahmulah.",
    image: "/images/greenhouse.jpg",
    unit: "bunch",
    priceMvr: 30,
    inStock: true,
    featured: false,
    sortOrder: 40,
    active: true,
  },
  {
    id: 5,
    slug: "sugarcane",
    name: "Sugarcane",
    kind: "Field",
    season: "Visit days",
    note: "Chewed fresh with visitors on the walk between rows.",
    image: "/images/farm-landscape.jpg",
    unit: "stick",
    priceMvr: 15,
    inStock: true,
    featured: false,
    sortOrder: 50,
    active: true,
  },
  {
    id: 6,
    slug: "nursery",
    name: "Nursery plants",
    kind: "Nursery",
    season: "Always",
    note: "Trays and bagged starts for island farmers, shared from the Meedhoo nursery.",
    image: "/images/nursery.jpg",
    unit: "tray",
    priceMvr: 40,
    inStock: true,
    featured: false,
    sortOrder: 60,
    active: true,
  },
];

export const DEFAULT_TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    quote:
      "Switching to island produce for our kitchen has made my week simpler. I cannot imagine going back to waiting on the boat.",
    name: "Mariyam A.",
    role: "Chef, Addu",
    tone: "sand",
    image: null,
    status: "published",
    sortOrder: 10,
  },
  {
    id: 2,
    quote:
      "Zuvaan Dhanduveriya has completely changed how we think about growing food on a small island. The greenhouse is quiet, exact, and generous.",
    name: "Ibrahim R.",
    role: "Meedhoo neighbour",
    tone: "photo",
    image: "/images/voice-ibrahim.jpg",
    status: "published",
    sortOrder: 20,
  },
  {
    id: 3,
    quote:
      "Thanks to this farm I feel in control of what we serve. Highly recommended for anyone serious about island food.",
    name: "Samantha K.",
    role: "Guest, Hulhumeedhoo",
    tone: "photo",
    image: "/images/voice-samantha.jpg",
    status: "published",
    sortOrder: 30,
  },
  {
    id: 4,
    quote:
      "I never thought this simple a farm visit could restore my confidence in local growing.",
    name: "Hassan D.",
    role: "Buyer, Fuvahmulah",
    tone: "photo",
    image: "/images/voice-hassan.jpg",
    status: "published",
    sortOrder: 40,
  },
  {
    id: 5,
    quote:
      "We tasted sugarcane between the rows. I left with a crate and a plan for next week's kitchen.",
    name: "Aisha F.",
    role: "Cook, Gan",
    tone: "photo",
    image: "/images/voice-aisha.jpg",
    status: "published",
    sortOrder: 50,
  },
  {
    id: 6,
    quote:
      "The cucumber from the greenhouse lasts days longer than anything that came off the ferry.",
    name: "Fathimath N.",
    role: "Home cook, Hithadhoo",
    tone: "dusk",
    image: null,
    status: "published",
    sortOrder: 60,
  },
  {
    id: 7,
    quote:
      "I walk the nursery whenever I am on Meedhoo. Plants leave with people who will actually grow them.",
    name: "Yoosuf M.",
    role: "Farmer, Hulhudhoo",
    tone: "lagoon",
    image: null,
    status: "published",
    sortOrder: 70,
  },
  {
    id: 8,
    quote:
      "Dragon fruit off the pillar, still warm from the morning. That is the whole argument for this farm.",
    name: "Hawwa S.",
    role: "Host, Addu",
    tone: "sage",
    image: null,
    status: "published",
    sortOrder: 80,
  },
];

export const DEFAULT_SOCIALS: SocialLink[] = [
  {
    id: 1,
    platform: "x",
    label: "X",
    url: "https://x.com/ZuvanDhaduveria",
    sortOrder: 10,
    active: true,
  },
  {
    id: 2,
    platform: "youtube",
    label: "YouTube",
    url: "https://www.youtube.com/@zuvaandhanduveriya",
    sortOrder: 20,
    active: true,
  },
  {
    id: 3,
    platform: "tiktok",
    label: "TikTok",
    url: "https://www.tiktok.com/@zuvaandhanduveriyaa",
    sortOrder: 30,
    active: true,
  },
];

export const DEFAULT_PARTNERS: Partner[] = [
  {
    id: 1,
    name: "Fresh Yield",
    license: "Pvt. Ltd. · farm licence",
    logo: "/images/partners/fresh-yield.svg",
    href: "",
    sortOrder: 10,
    active: true,
  },
  {
    id: 2,
    name: "Ooredoo",
    license: "Grow with Ooredoo",
    logo: "/images/partners/ooredoo.svg",
    href: "",
    sortOrder: 20,
    active: true,
  },
  {
    id: 3,
    name: "Addu City",
    license: "Municipal partner",
    logo: "/images/partners/addu-city.svg",
    href: "",
    sortOrder: 30,
    active: true,
  },
  {
    id: 4,
    name: "Meedhoo",
    license: "Host island",
    logo: "/images/partners/meedhoo.svg",
    href: "",
    sortOrder: 40,
    active: true,
  },
  {
    id: 5,
    name: "Fuvahmulah",
    license: "Kitchen supply",
    logo: "/images/partners/fuvahmulah.svg",
    href: "",
    sortOrder: 50,
    active: true,
  },
  {
    id: 6,
    name: "Island Farmers",
    license: "Nursery sharing",
    logo: "/images/partners/island-farmers.svg",
    href: "",
    sortOrder: 60,
    active: true,
  },
];

export const FALLBACK_CATALOG: Catalog = {
  products: DEFAULT_PRODUCTS,
  testimonials: DEFAULT_TESTIMONIALS,
  images: { ...SLOT_FALLBACK },
  socials: DEFAULT_SOCIALS,
  partners: DEFAULT_PARTNERS,
};
